# Generated by Django 5.1.3 on 2025-03-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypoll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
